apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.app.name }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         forward
        Listen       0.0.0.0
        Port         9880

    [OUTPUT]
        Name         stdout
        Match        *

---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: {{ .Values.app.name }}
spec:
  ports:
    - port: 9880
      targetPort: 9880
  selector:
    app: fluent-bit

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: {{ .Values.app.name }}
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: "fluent/fluent-bit:{{ .Values.app.database.fluentbit.version }}"
        ports:
        - containerPort: 9880
        volumeMounts:
        - name: config-volume
          mountPath: /fluent-bit/etc/
      volumes:
      - name: config-volume
        configMap:
          name: fluent-bit-config
