---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.app.name }}
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: notification-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.services.notification.replicas }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.app.services.notification.image }}
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/notification"
            - name: DB_USER
              value: {{ .Values.app.database.postgres.username }}
            - name: DB_PASSWORD
              value: {{ .Values.app.database.postgres.password }}
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_EXCHANGE
              value: {{ .Values.app.database.rabbitmq.exchange }}
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_ROUTING_KEYS_COLLECTION
              value: {{ .Values.app.services.notification.rabbitmq_routing_keys.collection }}
            - name: RABBITMQ_ROUTING_KEYS_REVIEW
              value: {{ .Values.app.services.notification.rabbitmq_routing_keys.review }}
            - name: RABBITMQ_ROUTING_KEYS_USER
              value: {{ .Values.app.services.notification.rabbitmq_routing_keys.user }}
            - name: RABBITMQ_QUEUE_COLLECTION
              value: {{ .Values.app.services.notification.rabbitmq_queue.collection }}
            - name: RABBITMQ_QUEUE_REVIEW
              value: {{ .Values.app.services.notification.rabbitmq_queue.review }}
            - name: RABBITMQ_QUEUE_USER
              value: {{ .Values.app.services.notification.rabbitmq_queue.user }}
            - name: GRPC_USER_SERVICE_HOST
              value: "user-service"
            - name: GRPC_USER_SERVICE_PORT
              value: "8081"

{{- if .Values.app.services.notification.ingress_host | default }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-service-ingress
  namespace: {{ .Values.app.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.app.services.notification.ingress_host | default }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
{{- end }}
