---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: {{ .Values.app.name }}
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: recipe-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  namespace: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.services.recipe.replicas }}
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: {{ .Values.app.services.recipe.image }}
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/recipe"
            - name: DB_USER
              value: {{ .Values.app.database.postgres.username }}
            - name: DB_PASSWORD
              value: {{ .Values.app.database.postgres.password }}
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: INGREDIENT_SERVICE_ADDRESS
              value: "ingredient-service:9090"
            - name: RABBIT_EXCHANGE
              value: {{ .Values.app.database.rabbitmq.exchange }}
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
            - name: REDIS_DATABASE
              value: {{ .Values.app.services.recipe.redis_database | quote }}

{{- if .Values.app.services.recipe.ingress_host | default }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-service-ingress
  namespace: {{ .Values.app.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.app.services.recipe.ingress_host | default }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8080
{{- end }}
