---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: {{ .Values.app.name }}
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: review-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.services.review.replicas }}
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: {{ .Values.app.services.review.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/review"
            - name: DB_USER
              value: {{ .Values.app.database.postgres.username }}
            - name: DB_PASSWORD
              value: {{ .Values.app.database.postgres.password }}
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: RABBIT_EXCHANGE
              value: {{ .Values.app.database.rabbitmq.exchange }}
            - name: USER_SERVICE_ADDRESS
              value: "user-service:8081"

{{- if .Values.app.services.review.ingress_host | default }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: review-service-ingress
  namespace: {{ .Values.app.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.app.services.review.ingress_host | default }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 8084
{{- end }}
