---
apiVersion: v1
kind: Service
metadata:
  name: shopping-list-service
  namespace: {{ .Values.app.name }}
spec:
  ports:
    - port: 3000
      name: http
    - port: 9009
      name: grpc
  selector:
    app: shopping-list-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-service
  namespace: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.services.shoppinglist.replicas }}
  selector:
    matchLabels:
      app: shopping-list-service
  template:
    metadata:
      labels:
        app: shopping-list-service
    spec:
      containers:
        - name: shopping-list-service
          image: {{ .Values.app.services.shoppinglist.image }}
          ports:
            - containerPort: 3000
            - containerPort: 9009
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: {{ .Values.app.database.postgres.username }}
            - name: DB_PASSWORD
              value: {{ .Values.app.database.postgres.password }}
            - name: DB_NAME
              value: {{ .Values.app.services.shoppinglist.database }}
            - name: RABBIT_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: RECIPE_SERVICE_ADDRESS
              value: "recipe-service:8080"
            - name: RABBIT_EXCHANGE
              value: {{ .Values.app.database.rabbitmq.exchange }}

{{- if .Values.app.services.shoppinglist.ingress_host | default }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-list-service-ingress
  namespace: {{ .Values.app.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.app.services.shoppinglist.ingress_host | default }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopping-list-service
                port:
                  number: 8080
{{- end }}
